### ISSUE TITLE
Start full Animation when in Viewport

### ISSUE THREAD

**Issue by graphek** [alexcambose/motus#50]
Hi there,

awesome library, i really like the approach. I'd also like to replace something like scrollreveal.js / aos.js with it, but i can't figure out how yet. 

It's possibles to immediately start the Animation: https://alexcambose.ro/motus/#/start-stop-animatios

But is it possible to start the Animiation and let in run through without taking the scroll position into consideration for a reveal effect?

An Option like "animateWhenInViewport" would be nice i guess

Best regards

**Comment by alexcambose** [comment]
Hi @graphek, thanks for the feedback.

I'm afraid what you are trying to do is not possible.

The thing is, Motus calculates the animation (aka "running the animation") **only** based on the scroll position. If you wouldn't be taking the scroll position into consideration, then there will be no animation.

Good luck with your project,
Alex
