### ISSUE TITLE
translateY function not working

### ISSUE THREAD

**Issue by nicklassandell** [alexcambose/motus#7]
I simply cannot get the translateY function to work. Following [the documentation](https://alexcambose.ro/motus/#/working-with-functions?id=transform) I should be able to do the following:

```
keyframes: {
        100: {
            translateY: ['-1000px']
        }
    }
```

But nothing happens. I tried with/without putting it in an array and with various values (positive/negative/different units). No dice. This is the only keyframe supplied, the element is not being transformed in any other way. Seems to be a bug with the css-func library?

**Comment by alexcambose** [comment]
Thanks for reporting.
